/*CC4Parser.java*/
package compiler.parser;
import java.io.*;
import java.util.*;
import compiler.lib.Printer;
import compiler.scanner.Scanner;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import compiler.scanner.DecafScanner;
import compiler.parser.DecafParser;
public class CC4Parser{
	Scanner s;
	private DecafParser parser;
	public CC4Parser(Printer out,String filename)throws Exception{
		this.s = new Scanner(out,filename);
		out.print("\nstage: parsing \n");

		try {	    
	      s.getScanner().reset();
	     this.parser = new DecafParser(new CommonTokenStream(s.getScanner()));

	     ParseTree tree = parser.program();

	     LinkedList<String> reglas = parser.list;

	     out.print("\n");

	     for(int i = 0; i<reglas.size(); i++){
	     	out.print("visited: " + reglas.get(i)+ "\n");
	     }

	     /*Printing parse tree 
	     	generated by antlr*/

	     out.print("\nParse tree: \n");
	     out.print(tree.toStringTree(parser));

	    } catch (ArrayIndexOutOfBoundsException aiobe) {
	      System.err.println("usage: java Main <file>\nwhere file is the path to the filename with the tokens");
	      System.exit(1);
	    } catch (Exception e) {
	      System.err.println("usage: java Main <file>\nwhere file is the path to the filename with the tokens");
	      System.exit(1);
	    } 
	    out.close();
	}
	public DecafParser getParser(){
		return this.parser;
	}
}